services:
  db:
    image: postgres:15
    container_name: mafia_postgres
    environment:
      POSTGRES_USER: mafia_user
      POSTGRES_PASSWORD: mafia_password
      POSTGRES_DB: mafia_db
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: mafia_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
