"""add basic room and room-related models

Revision ID: 001db45cf99b
Revises: 542764084002
Create Date: 2025-06-30 15:49:26.187636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001db45cf99b'
down_revision: Union[str, Sequence[str], None] = '542764084002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_mafia', sa.Boolean(), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rool_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mafia_percent', sa.SmallInteger(), nullable=False),
    sa.Column('allow_sherif', sa.Boolean(), nullable=False),
    sa.Column('day_duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('night_duration_minutes', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rool_sets_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rool_set_id', sa.Integer(), nullable=False),
    sa.Column('game_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_role_id'], ['game_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rool_set_id'], ['rool_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rool_set_id', 'game_role_id', name='unique_rool_set_game_role')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_', sa.Enum('PUBLIC', 'PRIVATE', name='roomtype'), nullable=False),
    sa.Column('rool_set_id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.UUID(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('player_limit', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rool_set_id'], ['rool_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_table('users_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'room_id', name='unqiue_user_room')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_rooms')
    op.drop_table('rooms')
    op.drop_table('rool_sets_roles')
    op.drop_table('rool_sets')
    op.drop_table('game_roles')
    # ### end Alembic commands ###
