"""add role to users

Revision ID: 4aa602093a57
Revises: c61e73b92af7
Create Date: 2025-07-07 02:47:53.252148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.user.enums import RoleChoices

# revision identifiers, used by Alembic.
revision: str = '4aa602093a57'
down_revision: Union[str, Sequence[str], None] = 'c61e73b92af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('role', sa.String(length=32), nullable=False, server_default=RoleChoices.USER.value)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
