"""remove flag is_private from Room model

Revision ID: cd91fb1ff12c
Revises: 001db45cf99b
Create Date: 2025-06-30 15:56:22.222264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd91fb1ff12c'
down_revision: Union[str, Sequence[str], None] = '001db45cf99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_private')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
